name:                ryu
version:             0.1.0.0
github:              "samueldurantes/ryu"
license:             BSD3
author:              "Samuel Durante"
maintainer:          "samueldurante00@gmail.com"
copyright:           "2023 Samuel Durante"

description:         idk 

dependencies:
- base >= 4.7 && < 5
- megaparsec
- containers

default-extensions:
  - LambdaCase

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  ryu-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
